### ISSUE TITLE
Respecto del README

### ISSUE THREAD

**Issue by delucas** [DeSkynet/jrpg#1]
Es necesario que lo completen con el enlace a sus nombres de usuario en GitHub, **respetando el formato de dejar un espacio entre palabra y paréntesis**. :)
Además, vayan pensando el nombre para el juego y agreguen un fragmento en el cual redactarán la pequeña historia que lo ambienta.

**Comment by williamleandro** [comment]
Buenas profe, ya se arregló los enlaces a nuestros nombres de usuario en el README, se agregó el nombre del juego, y en la semana estaremos agregando la historia. Saludos.

**Comment by delucas** [comment]
Entonces no está cerrado!
Habría que reabrirlo
