### ISSUE TITLE
Revisar la consistencia de las constantes numéricas

### ISSUE THREAD

**Issue by delucas** [DeSkynet/jrpg#2]
Con el código actual, es complicado leer los valores y asegurarse de que funcionan correctamente.
Utilizando algunas constantes, se puede mejorar tanto la legibilidad como la seguridad sobre el código desarrollado.

Por ejemplo, [aqui](https://github.com/DeSkynet/jrpg/blob/master/dominio/src/main/java/personaje/Robot.java) pueden ver que si el `Robot` tiene una `Casta` asignada, ataca con más fuerza, pero no necesariamente le consume más energía al hacerlo. Eso, ¿es intencional?

Adicionalmente, tanto el `5`, el `20` como el `200` deberían ser constantes. Y lo mismo para todas las demás clases del juego.

**Comment by JulyMorga** [comment]
Si, nos habiamos equivocado. Hemos corregido el error y subido la correccion. 
Saludos :)

**Comment by delucas** [comment]
Fijense bien lo de utilizar constantes...
