### ISSUE TITLE
Sobre la mensajeria

### ISSUE THREAD

**Issue by delucas** [DeSkynet/jrpg#3]
Reordenen la mensajería proporcionada.
Debería estar en el directorio `documentacion/mensajeria propuesta`, y allí ubiquen su archivo `.md`.

**Comment by williamleandro** [comment]
Listo profe, el archivo esta re localizado en [documentacion/mensajeria propuesta](https://github.com/DeSkynet/jrpg/tree/master/documentacion/mensajeria%20propuesta)  👍
