### ISSUE TITLE
Sobre las salidas por consola

### ISSUE THREAD

**Issue by delucas** [DeSkynet/jrpg#4]
No deben utilizar salidas del tipo `System.out.println`.
Como el juego no será en modo consola, todo eso se perderá al momento de establecer una interfaz.
Es mejor que no esté.

**Comment by williamleandro** [comment]
Se eliminaron todas las salidas!!!. Solo usamos `System.out.println` para verificar el correcto funcionamiento. Gracias por la sugerencia!
