### ISSUE TITLE
Sobre los comentarios en los commits

### ISSUE THREAD

**Issue by delucas** [DeSkynet/jrpg#6]
![image](https://cloud.githubusercontent.com/assets/684051/19831108/854da4e8-9dd8-11e6-9849-9fabe661bd1e.png)

Cuando se commitea, es preferible tener mensajes representativos de lo que se hizo, y no de los archivos que se han cambiado.
En el detalle del commit, es claro lo que cambió. Sin embargo, no es clara la intención que se tuvo.

Ejemplo:
"se modifica clase personaje", podría escribirse mucho mejor como "se agrega la habilidad de curarse al personaje", con todo lo que eso implica, y los tests correspondientes.

**Comment by williamleandro** [comment]
Gracias por la sugerencia profe!! Ya nos ocupamos de la persona que hizo esos commits  👊. 😀
